### ISSUE TITLE
Wrong Frame data Information

### ISSUE THREAD

**Issue by Vinay072** [WAZAAAAA0/TekkenBot#10]
Hi Team,

You're doing great job thanks for your efforts....

Actually I found that kazumi's ff+2 is actually -13 on block but bot is displaying it -16.
can you please recheck that and confirm us.

Thanks
Vinay

**Comment by WAZAAAAA0** [comment]
do me a favor willya

I'm gonna change the readme a bit next patch, see if this method helps:


***Q:*** *The frame advantage of this move seems wrong!*
***A:*** Double check using the alternative "manual" method to find frame advantage with the help of `tiny_live_frame_data_numbers`:
1. enable `Display -> tiny_live_frame_data_numbers` if it isn't already
2. start a mirror match in Practice Mode (mirror because not all characters share the same jumps)
3. do your attack, neutral jump, and don't do anything else
4. set the dummy to neutral jump as second action

...the little numbers near the big frame advantage ones should now hopefully display the correct advantage.
